const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');
const assert = require('assert');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const errors = [], api = [];
  const url = pathToFileURL(path.resolve(__dirname, '../docs/fusion/index.html')).href;
  for (const width of [1440, 390]) {
    const page = await browser.newPage({ viewport: { width, height: width === 390 ? 844 : 900 }, deviceScaleFactor: 1 });
    const action = name => page.locator(`[data-action="${name}"]:visible`).last().click();
    page.on('pageerror', e => errors.push(`${width}: ${e.message}`));
    page.on('request', r => { if (['fetch', 'xhr'].includes(r.resourceType())) api.push(r.url()); });
    await page.goto(url);
    assert(await page.getByText('红星市场榴莲到货事实').isVisible());
    if (width === 1440) await page.screenshot({ path: path.join(__dirname, 'fusion-home-desktop.png'), fullPage: true });
    else await page.screenshot({ path: path.join(__dirname, 'fusion-home-390.png'), fullPage: true });
    await action('from-source');
    assert(await page.getByText('配置推演输入').isVisible());
    await action('check');
    assert(await page.getByText('确认输入预览').isVisible());
    await page.screenshot({ path: path.join(__dirname, `fusion-preview-${width}.png`), fullPage: true });
    await action('confirm');
    assert(await page.getByText('推演工作台').isVisible());
    await action('next');
    await page.locator('.workspace [data-action="tab"][data-value="graph"]').click();
    assert(await page.getByLabel('模拟供应链图').isVisible());
    await page.locator('.workspace [data-action="tab"][data-value="workbench"]').click();
    for (let i = 0; i < 3; i++) await action('next');
    await page.screenshot({ path: path.join(__dirname, `fusion-workbench-${width}.png`), fullPage: true });
    await action('report');
    await action('source');
    assert(await page.getByText('引用来源 · 事实对象').isVisible());
    await action('back');
    assert(await page.getByText('推演报告 · 演示摘要').isVisible());
    await page.reload();
    await action('from-source');
    await page.locator('.workspace [data-action="entry"][data-value="path"]').click();
    await action('check');
    assert(await page.getByText('关系方向与路径').isVisible());
    await page.locator('[data-action="path-edge"]').uncheck();
    assert(await page.locator('.workspace [data-action="confirm"]').isDisabled());
    await page.locator('[data-action="path-edge"]').check();
    await action('confirm');
    assert(await page.getByText('推演工作台').isVisible());
    await page.reload();
    await action('from-source');
    await page.locator('.workspace [data-action="entry"][data-value="direct"]').click();
    await action('check');
    assert(await page.locator('.workspace [data-action="confirm"]').isDisabled());
    await page.locator('.workspace [data-action="edit"]').click();
    await page.locator('[data-field="region"]').fill('长沙 · 红星市场');
    await page.locator('[data-field="commodity"]').fill('榴莲');
    await page.locator('[data-field="from"]').fill('2026-09-01');
    await page.locator('[data-field="to"]').fill('2026-09-30');
    await page.locator('[data-field="goal"]').fill('观察示意供应链到货变化');
    await page.locator('[data-action="dataset"]').check();
    await action('check');
    assert(await page.locator('.workspace [data-action="confirm"]').isEnabled());
    await action('confirm');
    assert(await page.getByText('推演工作台').isVisible());
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth);
    assert(overflow <= 1, `horizontal overflow ${width}: ${overflow}`);
    await page.close();
  }
  await browser.close();
  assert.deepStrictEqual(errors, []);
  assert.deepStrictEqual(api, []);
  console.log('Browser paths passed at 1440px and 390px; no script errors, API requests, or horizontal overflow.');
})().catch(e => { console.error(e); process.exit(1); });
